---

- hosts: docker-host
  tasks:
  
  - name: Pull jenkins images
    command: docker pull jenkins:2.60.2

  - name: Create directory for jenkins
    file: 
      path: /docker/jenkins
      state: directory
      mode: 0755

  - name: Create docker-composes
    get_url: 
      url: https://github.com/dimastantowi/futuready-docker-compose/releases/download/Jenkins-v1.0.0/docker-compose.yml
      dest: /docker/jenkins/docker-compose.yml
      mode: 0755

  - name: Run jenkins container 
    command: docker-compose up -d
    args:
      chdir: /docker/jenkins
