---

- hosts: docker-host
  tasks:
  
  - name: Pull jenkins images
    command: docker pull jenkins:2.60.2

  - name: Create directory for jenkins
    file: 
      path: /docker/jenkins
      state: directory
      mode: 0755

  - name: Get docker-compose.yml for jenkins
    git:
      repo: 'https://github.com/dimzrio/docker-compose.git'
      dest: /opt/
